var exampleCities =
[ 'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Philadelphia',
  'Phoenix',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'San Francisco',
  'Indianapolis',
  'Columbus',
  'Fort Worth',
  'Charlotte',
  'Detroit',
  'El Paso',
  'Seattle',
  'Denver',
  'Washington DC',
  'Memphis',
  'Boston',
  'Nashville',
  'Baltimore'];

module.exports.exampleCities = exampleCities